import type { BindingTuple } from './SceneEntity.js';

export const BOAT_CHILD_BINDINGS: readonly BindingTuple[] = [
  { index: 0, id: 'hull.shell', name: 'Hull shell', group: 'hull' },
  { index: 1, id: 'hull.deck', name: 'Deck and cockpit moulding', group: 'hull' },
  { index: 2, id: 'hull.transom', name: 'Transom panel', group: 'hull' },
  { index: 3, id: 'hull.stem', name: 'Bow stem cap', group: 'hull' },
  { index: 4, id: 'hull.cockpit.sole', name: 'Cockpit sole', group: 'hull' },
  { index: 5, id: 'hull.cockpit.side.port', name: 'Port cockpit sidewall', group: 'hull' },
  { index: 6, id: 'hull.gunwale.port', name: 'Port inner gunwale', group: 'hull' },
  { index: 7, id: 'hull.bench.port', name: 'Port side deck', group: 'hull' },
  { index: 8, id: 'hull.cockpit.side.starboard', name: 'Starboard cockpit sidewall', group: 'hull' },
  { index: 9, id: 'hull.gunwale.starboard', name: 'Starboard inner gunwale', group: 'hull' },
  { index: 10, id: 'hull.bench.starboard', name: 'Starboard side deck', group: 'hull' },
  { index: 11, id: 'hull.forward-bulkhead', name: 'Forward cockpit bulkhead', group: 'hull' },
  { index: 12, id: 'hull.rubrail', name: 'Gunwale rub rail', group: 'hull' },
  { index: 13, id: 'hull.mast-collar', name: 'Mast step collar', group: 'hull' },
  { index: 14, id: 'hull.bow-fitting', name: 'Bow fitting', group: 'hull' },
  { index: 15, id: 'hull.chainplate.port', name: 'Port shroud chainplate', group: 'hull' },
  { index: 16, id: 'hull.chainplate.starboard', name: 'Starboard shroud chainplate', group: 'hull' },
  { index: 17, id: 'hull.transom-eye.port', name: 'Port transom eye', group: 'hull' },
  { index: 18, id: 'hull.transom-eye.starboard', name: 'Starboard transom eye', group: 'hull' },
  { index: 19, id: 'hull.mainsheet-swivel', name: 'Mainsheet swivel base', group: 'hull' },
  { index: 20, id: 'hull.hiking-strap.port', name: 'Port hiking strap', group: 'hull' },
  { index: 21, id: 'hull.hiking-strap.starboard', name: 'Starboard hiking strap', group: 'hull' },
  { index: 22, id: 'hull.jib-control.port', name: 'Port jib control fitting', group: 'hull' },
  { index: 23, id: 'hull.jib-control.starboard', name: 'Starboard jib control fitting', group: 'hull' },
  { index: 24, id: 'steering.centerboard', name: 'Centerboard blade', group: 'steering' },
  { index: 25, id: 'hull.centerboard-case', name: 'Centerboard case', group: 'hull' },
  { index: 26, id: 'steering.rudder-stock', name: 'Rudder stock and pivot', group: 'steering' },
  { index: 27, id: 'steering.tiller-extension', name: 'Tiller extension', group: 'steering' },
  { index: 28, id: 'hull.equipment-marker', name: 'Forward equipment marker', group: 'hull' },
  { index: 29, id: 'hull.bow-eye', name: 'Bow eye and handle', group: 'hull' },
  { index: 30, id: 'crew.helm', name: 'Helm', group: 'crew' },
  { index: 31, id: 'crew.forward', name: 'Forward crew', group: 'crew' },
];

export const RIG_CHILD_BINDINGS: readonly BindingTuple[] = [
  { index: 0, id: 'rig.mast', name: 'Mast', group: 'rig' },
  { index: 1, id: 'rig.boom', name: 'Boom', group: 'rig' },
  { index: 2, id: 'rig.spreader.port', name: 'Port spreader', group: 'rig' },
  { index: 3, id: 'rig.spreader.starboard', name: 'Starboard spreader', group: 'rig' },
  { index: 4, id: 'rig.shroud.upper.port', name: 'Port upper shroud', group: 'rig' },
  { index: 5, id: 'rig.shroud.upper.starboard', name: 'Starboard upper shroud', group: 'rig' },
  { index: 6, id: 'rig.shroud.lower.port', name: 'Port lower shroud', group: 'rig' },
  { index: 7, id: 'rig.shroud.lower.starboard', name: 'Starboard lower shroud', group: 'rig' },
  { index: 8, id: 'rig.forestay', name: 'Forestay', group: 'rig' },
];
