import { readFileSync } from 'node:fs';
const root = '/home/user/aqua-react-splash/laser2/';
const K = await import(root + 'dist/src/crew/lucid/LucidKinematics.js');
const header = JSON.parse(readFileSync(root + 'public/assets/lucid/lucid_female_v4_2.json', 'utf8'));
const asset = { header, jointIndex: new Map(header.joints.map((n, i) => [n, i])) };
const body = new K.Semantic51Body(asset);
const j = asset.jointIndex.get('L_Upperarm');
console.log('dofs', body.jointDofs[j].map((d) => [header.semantic51[d.index].id, d.axis.map((v) => +v.toFixed(3))]));
const sem = new Float64Array(header.semantic51.length), hand = new Float64Array(header.handDofs.length);
const target = K.m3();
body.solveLocal(j, target, sem, hand, 8);
console.log('identity ->', body.jointDofs[j].map((d) => +sem[d.index].toFixed(3)));
const abd = body.jointDofs[j][1];
K.m3AxisAngle(abd.axis[0], abd.axis[1], abd.axis[2], 20 * Math.PI / 180, target);
sem.fill(0);
body.solveLocal(j, target, sem, hand, 8);
console.log('abd20 ->', body.jointDofs[j].map((d) => +sem[d.index].toFixed(3)));
const fl = body.jointDofs[j][0];
const t2 = K.m3(); K.m3AxisAngle(fl.axis[0], fl.axis[1], fl.axis[2], 50 * Math.PI / 180, t2);
const t3 = K.m3(); K.m3Mul(t2, target, t3);
sem.fill(0);
body.solveLocal(j, t3, sem, hand, 8);
console.log('flex50*abd20 ->', body.jointDofs[j].map((d) => +sem[d.index].toFixed(3)));
