export interface LightingSettings {
  atmosphereEnabled: boolean;
  sunElevationDeg: number;
  sunAzimuthDeg: number;
  sunIlluminanceLux: number;
  sunIntensity: number;
  sunAngularRadiusDeg: number;
  skyIntensity: number;
  rayleighDensity: number;
  aerosolDensity: number;
  mieAnisotropy: number;
  turbidity: number;
  ozoneDensity: number;
  multipleScatteringFactor: number;
  spectralSolarEnabled: boolean;
  groundAlbedo: number;
  groundBounce: number;
  cameraAltitudeM: number;
  exposureEv: number;
  autoExposureEnabled: boolean;
  autoExposureReferenceLux: number;
  autoExposureStrength: number;
  autoExposureMinEv: number;
  autoExposureMaxEv: number;
  whiteBalanceKelvin: number;
  toneMappingShoulder: number;
  aerialPerspectiveEnabled: boolean;
  aerialPerspectiveStrength: number;
  aerialPerspectiveMaxDistanceM: number;
  diffuseEnvironmentIntensity: number;
  specularEnvironmentIntensity: number;
  localProbesEnabled: boolean;
  localDiffuseBounceStrength: number;
  localSpecularProbeStrength: number;
  shadowsEnabled: boolean;
  sailTransmission: number;
  sailAbsorption: number;
  sailShadowSoftnessMm: number;
  vinylTransmission: number;
  aluminumRoughness: number;
  hullGelcoatRoughness: number;
}

export const DEFAULT_LIGHTING_SETTINGS: LightingSettings = {
  atmosphereEnabled: true,
  sunElevationDeg: 38,
  sunAzimuthDeg: 145,
  sunIlluminanceLux: 100_000,
  sunIntensity: 3.2,
  sunAngularRadiusDeg: 0.266,
  skyIntensity: 0.92,
  rayleighDensity: 1.0,
  aerosolDensity: 0.34,
  mieAnisotropy: 0.76,
  turbidity: 2.8,
  ozoneDensity: 1.0,
  multipleScatteringFactor: 0.42,
  spectralSolarEnabled: true,
  groundAlbedo: 0.16,
  groundBounce: 0.18,
  cameraAltitudeM: 2,
  exposureEv: 0,
  autoExposureEnabled: false,
  autoExposureReferenceLux: 20_000,
  autoExposureStrength: 0.72,
  autoExposureMinEv: -3,
  autoExposureMaxEv: 4,
  whiteBalanceKelvin: 6500,
  toneMappingShoulder: 1.0,
  aerialPerspectiveEnabled: true,
  aerialPerspectiveStrength: 0.72,
  aerialPerspectiveMaxDistanceM: 1800,
  diffuseEnvironmentIntensity: 1.0,
  specularEnvironmentIntensity: 1.0,
  localProbesEnabled: true,
  localDiffuseBounceStrength: 0.85,
  localSpecularProbeStrength: 0.55,
  shadowsEnabled: true,
  sailTransmission: 0.27,
  sailAbsorption: 0.42,
  sailShadowSoftnessMm: 55,
  vinylTransmission: 0.92,
  aluminumRoughness: 0.32,
  hullGelcoatRoughness: 0.22,
};
